name: "Main Workflow"
on:
  pull_request:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Build & Test'
      uses: ashutoshvarma/action-cmake-build@master
      with:
        cc: gcc
        cxx: g++
        build-type: Release
        configure-options: -DBUILD_TESTING=1
        run-test: true
